#!/bin/bash

home="$(dirname "$(readlink -f $0)")"
repo="${home}/repo"

totalPackages=$(find ${repo} -type f -name '*.pkg.tar.?z' | wc -l)

gzPackages=$(find ${repo} -type f -name '*.pkg.tar.gz' | wc -l)
gzPercentage=$(echo "scale=4; ${gzPackages}/${totalPackages}*100" | bc)

xzPackages=$(find ${repo} -type f -name '*.pkg.tar.xz' | wc -l)
xzPercentage=$(echo "scale=4; ${xzPackages}/${totalPackages}*100" | bc)

signedPackages=$(find ${repo} -type f -name '*.pkg.tar.?z.sig' | wc -l)
signedPercentage=$(echo "scale=4; ${signedPackages}/${totalPackages}*100" | bc)

pooledPackages=$(find ${repo}/pool -type f -name '*.pkg.tar.?z' | wc -l)
pooledPercentage=$(echo "scale=4; ${pooledPackages}/${totalPackages}*100" | bc)

echo -e "\t\tpackages\tpercentage"
echo -e "total\t\t${totalPackages}"
echo -e "pooled\t\t${pooledPackages}\t\t${pooledPercentage}%"
echo -e "xz\t\t${xzPackages}\t\t${xzPercentage}%"
echo -e "gzip\t\t${gzPackages}\t\t${gzPercentage}%"
echo -e "signed\t\t${signedPackages}\t\t${signedPercentage}%"
