#!/bin/bash

home="$(dirname "$(readlink -f $0)")"
target="${home}/repo"
tmp="${home}/tmp"
lock='/tmp/mirrorsync.lck'
source='rsync://mirror.de.leaseweb.net/archlinux/'

[ ! -d "${target}" ] && mkdir -p "${target}"
[ ! -d "${tmp}" ] && mkdir -p "${tmp}"
[ -f "${lock}" ] && exit 1
touch "${lock}"
trap "rm -f '${lock}'" EXIT INT TERM

rsync -rtlvHy --safe-links --delete-after -h \
	--delay-updates --no-motd --bwlimit=4096 \
	--temp-dir="${tmp}" \
	--exclude='*.links.tar.gz' \
	--exclude='*.old' \
	--exclude='/other' \
	--exclude='/sources' \
	--exclude='/iso' \
	--exclude='/project' \
	--exclude='/Archive-Update-*-mirror.de.leaseweb.net' \
	${source} \
	"${target}"

echo "Last sync was   $(date -d @$(cat ${target}/lastsync))"
echo "Last update was $(date -d @$(cat ${target}/lastupdate))"
